import type {
  Attachment,
  DevOpsLink,
  JiraLink,
  Project,
  ProjectChange,
  ProjectMember,
  PullRequest,
  UserStory,
} from './types'

export const mockMembersPool: ProjectMember[] = [
  { id: 'u-101', name: 'María P.', initials: 'MP' },
  { id: 'u-102', name: 'Carlos R.', initials: 'CR' },
  { id: 'u-103', name: 'Ana G.', initials: 'AG' },
  { id: 'u-104', name: 'Jorge V.', initials: 'JV' },
  { id: 'u-105', name: 'Luisa F.', initials: 'LF' },
  { id: 'u-106', name: 'Ricardo M.', initials: 'RM' },
  { id: 'u-107', name: 'Sofía L.', initials: 'SL' },
  { id: 'u-108', name: 'Diego G.', initials: 'DG' },
  { id: 'u-109', name: 'Elena B.', initials: 'EB' },
  { id: 'u-110', name: 'Pablo N.', initials: 'PN' },
]

export const mockProjects: Project[] = [
  {
    id: 'p-001',
    code: 'PR001',
    name: 'API Solicitudes',
    description:
      'Servicio REST para la gestión de solicitudes de crédito de clientes personales y empresariales.',
    status: 'Activo',
    owner: { id: 'u-101', name: 'María P.', initials: 'MP' },
    lastUpdate: '15/03/2026',
    changesCount: 42,
    prCount: 8,
    docsCount: 14,
    tech: ['.NET 8', 'SQL Server', 'Azure'],
  },
  {
    id: 'p-002',
    code: 'PR002',
    name: 'Portal Cliente',
    description:
      'Portal transaccional para clientes con autenticación SSO, consultas y operaciones.',
    status: 'Activo',
    owner: { id: 'u-102', name: 'Carlos R.', initials: 'CR' },
    lastUpdate: '12/03/2026',
    changesCount: 67,
    prCount: 12,
    docsCount: 21,
    tech: ['React', 'TypeScript', 'Node'],
  },
  {
    id: 'p-003',
    code: 'PR003',
    name: 'Motor de Pagos',
    description:
      'Orquestador de pagos integrado con ACH, tarjetas y billeteras digitales.',
    status: 'Activo',
    owner: { id: 'u-103', name: 'Ana G.', initials: 'AG' },
    lastUpdate: '10/03/2026',
    changesCount: 128,
    prCount: 5,
    docsCount: 33,
    tech: ['Java', 'Kafka', 'PostgreSQL'],
  },
  {
    id: 'p-004',
    code: 'PR004',
    name: 'Data Warehouse',
    description: 'Repositorio analítico centralizado con pipelines ETL diarios.',
    status: 'En pausa',
    owner: { id: 'u-104', name: 'Jorge V.', initials: 'JV' },
    lastUpdate: '28/02/2026',
    changesCount: 19,
    prCount: 2,
    docsCount: 9,
    tech: ['Python', 'Airflow', 'Snowflake'],
  },
  {
    id: 'p-005',
    code: 'PR005',
    name: 'Mobile Banking',
    description: 'Aplicación móvil oficial para iOS y Android del banco.',
    status: 'Activo',
    owner: { id: 'u-105', name: 'Luisa F.', initials: 'LF' },
    lastUpdate: '14/03/2026',
    changesCount: 88,
    prCount: 6,
    docsCount: 18,
    tech: ['React Native', 'Swift', 'Kotlin'],
  },
  {
    id: 'p-006',
    code: 'PR006',
    name: 'Core Bancario',
    description: 'Sistema central de cuentas, transacciones y conciliaciones.',
    status: 'Activo',
    owner: { id: 'u-106', name: 'Ricardo M.', initials: 'RM' },
    lastUpdate: '13/03/2026',
    changesCount: 251,
    prCount: 4,
    docsCount: 47,
    tech: ['COBOL', 'DB2', 'AIX'],
  },
]

export const mockChanges: Record<string, ProjectChange[]> = {
  'p-001': [
    {
      id: 'c-001',
      date: '12 Abr 2026',
      type: 'Mejora',
      title: 'Actualización de validación de dirección',
      description: 'Se actualizó el servicio de validación con la nueva integración de Google Maps.',
      huRefs: ['HU-120', 'HU-450'],
      prRefs: ['PR-450'],
      author: { id: 'u-101', name: 'María P.', initials: 'MP' },
      environment: 'QA',
      version: '1.5.2',
      comment: {
        author: { id: 'u-102', name: 'Carlos R.', initials: 'CR' },
        text: 'Pruebas en QA completadas correctamente.',
      },
    },
    {
      id: 'c-002',
      date: '10 Abr 2026',
      type: 'Bugfix',
      title: 'Corrección error ORA-01403',
      description: 'Se corrigió la consulta que no manejaba el caso cuando no hay registros.',
      huRefs: ['HU-115'],
      prRefs: ['PR-432'],
      author: { id: 'u-103', name: 'Diego G.', initials: 'DG' },
      environment: 'DEV',
      version: '1.5.1',
      comment: {
        author: { id: 'u-101', name: 'María P.', initials: 'MP' },
        text: 'Revisado. Queda pendiente agregar un test de regresión para el caso sin registros.',
      },
    },
    {
      id: 'c-003',
      date: '05 Abr 2026',
      type: 'Refactor',
      title: 'Refactor del módulo de scoring',
      description: 'Migración de scoring sincrónico a colas para mejorar tiempos de respuesta.',
      huRefs: ['HU-098'],
      prRefs: ['PR-421'],
      author: { id: 'u-101', name: 'María P.', initials: 'MP' },
      environment: 'DEV',
      version: '1.5.0',
      comment: {
        author: { id: 'u-104', name: 'Jorge V.', initials: 'JV' },
        text: 'Me preocupan los tiempos cuando la cola está vacía. Agregar métricas con Application Insights.',
      },
    },
  ],
  'p-002': [
    {
      id: 'c-101',
      date: '13 Abr 2026',
      type: 'Mejora',
      title: 'Migración del login a MSAL',
      description:
        'Se reemplazó el flujo de autenticación propio por Microsoft Entra ID (MSAL).',
      huRefs: ['HU-211'],
      prRefs: ['PR-512'],
      author: { id: 'u-102', name: 'Carlos R.', initials: 'CR' },
      environment: 'QA',
      version: '2.4.0',
      comment: {
        author: { id: 'u-101', name: 'María P.', initials: 'MP' },
        text: 'SSO probado con cuentas corporativas.',
      },
    },
    {
      id: 'c-102',
      date: '11 Abr 2026',
      type: 'Bugfix',
      title: 'Fix en expiración de sesión',
      description: 'Se corrigió la validación del token cuando expiraba en segundo plano.',
      huRefs: ['HU-215'],
      prRefs: ['PR-509'],
      author: { id: 'u-102', name: 'Carlos R.', initials: 'CR' },
      environment: 'DEV',
      version: '2.3.9',
    },
    {
      id: 'c-103',
      date: '08 Abr 2026',
      type: 'Feature',
      title: 'Nueva sección de notificaciones',
      description:
        'Se incorporó el panel de notificaciones con filtros por tipo y marcado como leído.',
      huRefs: ['HU-220', 'HU-221'],
      prRefs: ['PR-502'],
      author: { id: 'u-105', name: 'Luisa F.', initials: 'LF' },
      environment: 'UAT',
      version: '2.3.5',
      comment: {
        author: { id: 'u-102', name: 'Carlos R.', initials: 'CR' },
        text: 'Validado en UAT con el equipo de producto. Listo para PROD después del freeze.',
      },
    },
  ],
  'p-003': [
    {
      id: 'c-201',
      date: '12 Abr 2026',
      type: 'Bugfix',
      title: 'Corrección en validación de montos ACH',
      description:
        'Se añadió la validación de montos negativos y redondeo en transferencias ACH.',
      huRefs: ['HU-305'],
      prRefs: ['PR-612'],
      author: { id: 'u-103', name: 'Ana G.', initials: 'AG' },
      environment: 'PROD',
      version: '4.1.2',
      comment: {
        author: { id: 'u-106', name: 'Ricardo M.', initials: 'RM' },
        text: 'Importante: revisar si aplica el mismo fix al flujo batch nocturno.',
      },
    },
    {
      id: 'c-202',
      date: '09 Abr 2026',
      type: 'Feature',
      title: 'Soporte para billeteras digitales',
      description:
        'Se habilitó la conexión con proveedores de billeteras locales mediante webhooks.',
      huRefs: ['HU-310'],
      prRefs: ['PR-605'],
      author: { id: 'u-103', name: 'Ana G.', initials: 'AG' },
      environment: 'UAT',
      version: '4.1.0',
    },
  ],
  'p-005': [
    {
      id: 'c-301',
      date: '14 Abr 2026',
      type: 'Docs',
      title: 'Documentación del flujo de onboarding',
      description:
        'Se agregaron diagramas de secuencia y capturas del nuevo proceso de onboarding móvil.',
      huRefs: ['HU-420'],
      prRefs: ['PR-703'],
      author: { id: 'u-105', name: 'Luisa F.', initials: 'LF' },
      environment: 'DEV',
      version: '3.2.1',
      comment: {
        author: { id: 'u-102', name: 'Carlos R.', initials: 'CR' },
        text: 'Excelente. Sugiero referenciar la HU-211 (MSAL) para que quede claro el ciclo completo.',
      },
    },
    {
      id: 'c-302',
      date: '11 Abr 2026',
      type: 'Mejora',
      title: 'Push notifications con Firebase',
      description:
        'Integración de FCM para notificaciones push al aprobar solicitudes.',
      huRefs: ['HU-421'],
      prRefs: ['PR-702'],
      author: { id: 'u-105', name: 'Luisa F.', initials: 'LF' },
      environment: 'QA',
      version: '3.2.0',
    },
  ],
  'p-006': [
    {
      id: 'c-401',
      date: '07 Abr 2026',
      type: 'Refactor',
      title: 'Migración a nueva versión de DB2',
      description: 'Se actualizaron las utilerías del core al nuevo cliente DB2 12.1.',
      huRefs: ['HU-510'],
      prRefs: ['PR-801'],
      author: { id: 'u-106', name: 'Ricardo M.', initials: 'RM' },
      environment: 'UAT',
      version: '8.7.0',
      comment: {
        author: { id: 'u-103', name: 'Ana G.', initials: 'AG' },
        text: 'Rollback plan documentado en el adjunto db2_migration_plan.pdf. Aprobado para PROD.',
      },
    },
  ],
}

export const mockJiraLinks: Record<string, JiraLink[]> = {
  'p-001': [
    { id: 'j-1', key: 'HU-120', title: 'Validar Dirección – Jira' },
    { id: 'j-2', key: 'HU-450', title: 'Integración Google Maps' },
    { id: 'j-3', key: 'HU-115', title: 'Bug consulta clientes' },
  ],
}

export const mockDevOpsLinks: Record<string, DevOpsLink[]> = {
  'p-001': [
    { id: 'd-1', prNumber: 450, title: 'Azure DevOps · Refactor Dirección' },
    { id: 'd-2', prNumber: 432, title: 'Azure DevOps · Fix Query' },
    { id: 'd-3', prNumber: 421, title: 'Azure DevOps · Scoring async' },
  ],
}

export const mockAttachments: Record<string, Attachment[]> = {
  'p-001': [
    {
      id: 'a-1',
      name: 'script_validacion_direccion.sql',
      size: '24 KB',
      uploadedAt: '12/04/2026',
      uploadedBy: { id: 'u-101', name: 'María P.', initials: 'MP' },
    },
    {
      id: 'a-2',
      name: 'Pruebas_QA_HU-120.png',
      size: '318 KB',
      uploadedAt: '12/04/2026',
      uploadedBy: { id: 'u-102', name: 'Carlos R.', initials: 'CR' },
    },
    {
      id: 'a-3',
      name: 'diagrama-flujo-solicitudes.pdf',
      size: '1.2 MB',
      uploadedAt: '10/04/2026',
      uploadedBy: { id: 'u-101', name: 'María P.', initials: 'MP' },
    },
    {
      id: 'a-4',
      name: 'plan_pruebas.xlsx',
      size: '88 KB',
      uploadedAt: '08/04/2026',
      uploadedBy: { id: 'u-103', name: 'Ana G.', initials: 'AG' },
    },
    {
      id: 'a-5',
      name: 'postman_collection.json',
      size: '12 KB',
      uploadedAt: '06/04/2026',
      uploadedBy: { id: 'u-101', name: 'María P.', initials: 'MP' },
    },
    {
      id: 'a-6',
      name: 'arquitectura_scoring.drawio',
      size: '44 KB',
      uploadedAt: '05/04/2026',
      uploadedBy: { id: 'u-102', name: 'Carlos R.', initials: 'CR' },
    },
    {
      id: 'a-7',
      name: 'logs_error_ora01403.txt',
      size: '6 KB',
      uploadedAt: '04/04/2026',
      uploadedBy: { id: 'u-103', name: 'Ana G.', initials: 'AG' },
    },
    {
      id: 'a-8',
      name: 'mockup_pantalla_resultado.png',
      size: '512 KB',
      uploadedAt: '01/04/2026',
      uploadedBy: { id: 'u-105', name: 'Luisa F.', initials: 'LF' },
    },
  ],
  'p-002': [
    {
      id: 'a-101',
      name: 'msal_configuracion.md',
      size: '18 KB',
      uploadedAt: '13/04/2026',
      uploadedBy: { id: 'u-102', name: 'Carlos R.', initials: 'CR' },
    },
    {
      id: 'a-102',
      name: 'captura_sso_exito.png',
      size: '420 KB',
      uploadedAt: '13/04/2026',
      uploadedBy: { id: 'u-102', name: 'Carlos R.', initials: 'CR' },
    },
    {
      id: 'a-103',
      name: 'checklist_release_2.4.xlsx',
      size: '62 KB',
      uploadedAt: '11/04/2026',
      uploadedBy: { id: 'u-101', name: 'María P.', initials: 'MP' },
    },
    {
      id: 'a-104',
      name: 'flujo_notificaciones.drawio',
      size: '54 KB',
      uploadedAt: '08/04/2026',
      uploadedBy: { id: 'u-105', name: 'Luisa F.', initials: 'LF' },
    },
  ],
  'p-003': [
    {
      id: 'a-201',
      name: 'contrato_ach_v2.pdf',
      size: '2.1 MB',
      uploadedAt: '12/04/2026',
      uploadedBy: { id: 'u-103', name: 'Ana G.', initials: 'AG' },
    },
    {
      id: 'a-202',
      name: 'webhook_billetera.json',
      size: '4 KB',
      uploadedAt: '09/04/2026',
      uploadedBy: { id: 'u-103', name: 'Ana G.', initials: 'AG' },
    },
    {
      id: 'a-203',
      name: 'logs_transacciones_prod.txt',
      size: '1.8 MB',
      uploadedAt: '12/04/2026',
      uploadedBy: { id: 'u-106', name: 'Ricardo M.', initials: 'RM' },
    },
  ],
  'p-005': [
    {
      id: 'a-301',
      name: 'onboarding_storyboard.pdf',
      size: '3.4 MB',
      uploadedAt: '14/04/2026',
      uploadedBy: { id: 'u-105', name: 'Luisa F.', initials: 'LF' },
    },
    {
      id: 'a-302',
      name: 'firebase_credentials.json',
      size: '2 KB',
      uploadedAt: '11/04/2026',
      uploadedBy: { id: 'u-105', name: 'Luisa F.', initials: 'LF' },
    },
    {
      id: 'a-303',
      name: 'push_notification_mockup.png',
      size: '620 KB',
      uploadedAt: '10/04/2026',
      uploadedBy: { id: 'u-105', name: 'Luisa F.', initials: 'LF' },
    },
  ],
  'p-006': [
    {
      id: 'a-401',
      name: 'db2_migration_plan.pdf',
      size: '1.1 MB',
      uploadedAt: '07/04/2026',
      uploadedBy: { id: 'u-106', name: 'Ricardo M.', initials: 'RM' },
    },
    {
      id: 'a-402',
      name: 'script_upgrade.sql',
      size: '88 KB',
      uploadedAt: '07/04/2026',
      uploadedBy: { id: 'u-106', name: 'Ricardo M.', initials: 'RM' },
    },
  ],
}

const u101: ProjectMember = { id: 'u-101', name: 'María P.', initials: 'MP' }
const u102: ProjectMember = { id: 'u-102', name: 'Carlos R.', initials: 'CR' }
const u103: ProjectMember = { id: 'u-103', name: 'Ana G.', initials: 'AG' }
const u104: ProjectMember = { id: 'u-104', name: 'Jorge V.', initials: 'JV' }
const u105: ProjectMember = { id: 'u-105', name: 'Luisa F.', initials: 'LF' }

export const mockUserStories: Record<string, UserStory[]> = {
  'p-001': [
    {
      id: 'hu-001',
      projectId: 'p-001',
      key: 'HU-120',
      title: 'Validar dirección contra API de Google Maps',
      description:
        'Como usuario, quiero que mi dirección se valide automáticamente al enviarla para evitar errores de captura.',
      status: 'Hecho',
      priority: 'Alta',
      assignee: u101,
      sprint: 'Sprint 24',
      storyPoints: 5,
      createdAt: '01 Mar 2026',
      updatedAt: '12 Abr 2026',
      linkedChangeIds: ['c-001'],
    },
    {
      id: 'hu-002',
      projectId: 'p-001',
      key: 'HU-115',
      title: 'Manejar caso de consulta sin resultados (ORA-01403)',
      description:
        'Como usuario, quiero recibir un mensaje claro cuando no existan registros en lugar de ver un error técnico.',
      status: 'Hecho',
      priority: 'Alta',
      assignee: u103,
      sprint: 'Sprint 24',
      storyPoints: 3,
      createdAt: '28 Feb 2026',
      updatedAt: '10 Abr 2026',
      linkedChangeIds: ['c-002'],
    },
    {
      id: 'hu-003',
      projectId: 'p-001',
      key: 'HU-098',
      title: 'Migrar scoring a colas para mejorar tiempos de respuesta',
      description:
        'Como sistema, necesito desacoplar el scoring del flujo sincrónico para reducir la latencia percibida por el usuario.',
      status: 'QA',
      priority: 'Alta',
      assignee: u101,
      sprint: 'Sprint 23',
      storyPoints: 8,
      createdAt: '15 Feb 2026',
      updatedAt: '05 Abr 2026',
      linkedChangeIds: ['c-003'],
    },
    {
      id: 'hu-004',
      projectId: 'p-001',
      key: 'HU-145',
      title: 'Reporte consolidado de solicitudes por sucursal',
      description:
        'Como gerente, quiero ver un reporte por sucursal con el total de solicitudes por estado y monto acumulado.',
      status: 'En progreso',
      priority: 'Media',
      assignee: u102,
      sprint: 'Sprint 25',
      storyPoints: 5,
      createdAt: '20 Mar 2026',
      updatedAt: '11 Abr 2026',
      linkedChangeIds: [],
    },
    {
      id: 'hu-005',
      projectId: 'p-001',
      key: 'HU-150',
      title: 'Notificación push al aprobar una solicitud',
      description:
        'Como cliente, quiero recibir una notificación push cuando mi solicitud sea aprobada.',
      status: 'En revisión',
      priority: 'Media',
      assignee: u104,
      sprint: 'Sprint 25',
      storyPoints: 3,
      createdAt: '22 Mar 2026',
      updatedAt: '12 Abr 2026',
      linkedChangeIds: [],
    },
    {
      id: 'hu-006',
      projectId: 'p-001',
      key: 'HU-158',
      title: 'Soporte multi-idioma en mensajes de error',
      description:
        'Como usuario, quiero ver los mensajes de error en mi idioma preferido (ES/EN).',
      status: 'Backlog',
      priority: 'Baja',
      assignee: u105,
      sprint: 'Sprint 26',
      storyPoints: 2,
      createdAt: '01 Abr 2026',
      updatedAt: '01 Abr 2026',
      linkedChangeIds: [],
    },
  ],
}

export const mockPullRequests: Record<string, PullRequest[]> = {
  'p-001': [
    {
      id: 'pr-001',
      projectId: 'p-001',
      number: 450,
      title: 'feat(address): integrar validación con Google Maps',
      branch: 'feature/validacion-direccion',
      targetBranch: 'main',
      status: 'Merged',
      author: u101,
      reviewers: [u102, u103],
      createdAt: '08 Abr 2026',
      updatedAt: '12 Abr 2026',
      additions: 284,
      deletions: 127,
      filesChanged: 12,
      commentsCount: 9,
      linkedHuKeys: ['HU-120'],
      checks: [
        { name: 'build', status: 'passed' },
        { name: 'typecheck', status: 'passed' },
        { name: 'test', status: 'passed' },
        { name: 'lint', status: 'passed' },
      ],
    },
    {
      id: 'pr-002',
      projectId: 'p-001',
      number: 432,
      title: 'fix(query): manejar consulta sin resultados en clientes',
      branch: 'bugfix/ora-01403',
      targetBranch: 'main',
      status: 'Merged',
      author: u103,
      reviewers: [u101],
      createdAt: '05 Abr 2026',
      updatedAt: '10 Abr 2026',
      additions: 42,
      deletions: 18,
      filesChanged: 3,
      commentsCount: 4,
      linkedHuKeys: ['HU-115'],
      checks: [
        { name: 'build', status: 'passed' },
        { name: 'typecheck', status: 'passed' },
        { name: 'test', status: 'passed' },
        { name: 'lint', status: 'passed' },
      ],
    },
    {
      id: 'pr-003',
      projectId: 'p-001',
      number: 421,
      title: 'refactor(scoring): migrar a procesamiento asíncrono',
      branch: 'refactor/scoring-async',
      targetBranch: 'main',
      status: 'En revisión',
      author: u101,
      reviewers: [u102, u105],
      createdAt: '01 Abr 2026',
      updatedAt: '11 Abr 2026',
      additions: 518,
      deletions: 342,
      filesChanged: 24,
      commentsCount: 18,
      linkedHuKeys: ['HU-098'],
      checks: [
        { name: 'build', status: 'passed' },
        { name: 'typecheck', status: 'passed' },
        { name: 'test', status: 'failed' },
        { name: 'lint', status: 'passed' },
      ],
    },
    {
      id: 'pr-004',
      projectId: 'p-001',
      number: 458,
      title: 'feat(notifications): push al aprobar solicitud',
      branch: 'feature/push-aprobacion',
      targetBranch: 'main',
      status: 'Cambios pedidos',
      author: u104,
      reviewers: [u101, u103],
      createdAt: '06 Abr 2026',
      updatedAt: '12 Abr 2026',
      additions: 156,
      deletions: 22,
      filesChanged: 8,
      commentsCount: 12,
      linkedHuKeys: ['HU-150'],
      checks: [
        { name: 'build', status: 'passed' },
        { name: 'typecheck', status: 'passed' },
        { name: 'test', status: 'running' },
        { name: 'lint', status: 'passed' },
      ],
    },
  ],
}
